import React, { useState } from "react";
import { Heart, MessageCircle, PenLine, Users } from "lucide-react";

const starterPosts = [
  { id: "welcome", author: "IOI Teacher Team", initials: "IO", time: "Today", title: "What are you practising this week?", body: "Share one English speaking goal with the community. A clear, small target makes progress easier to notice.", likes: 24, replies: 8 },
  { id: "shadowing", author: "Mina K.", initials: "MK", time: "Yesterday", title: "Shadowing helped my rhythm", body: "I listened to one short dialogue three times, then repeated it without looking. My pauses felt much more natural.", likes: 17, replies: 5 },
  { id: "interview", author: "Daniel R.", initials: "DR", time: "2 days ago", title: "Interview practice partners", body: "Looking for a partner to practise concise answers to common interview questions at B1–B2 level.", likes: 11, replies: 3 },
];

export const CommunityView: React.FC<{ isAuthenticated: boolean; onSignIn: () => void }> = ({ isAuthenticated, onSignIn }) => {
  const [posts, setPosts] = useState(starterPosts);
  const [liked, setLiked] = useState<string[]>([]);
  const [draft, setDraft] = useState("");
  const toggleLike = (id: string) => setLiked((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const submitPost = () => { const body = draft.trim(); if (!body) return; setPosts((current) => [{ id: `local-${Date.now()}`, author: "You", initials: "YO", time: "Just now", title: "A new practice note", body, likes: 0, replies: 0 }, ...current]); setDraft(""); };
  return <div className="space-y-5 p-4 sm:p-6"><section className="rounded-3xl border border-cyan-500/20 bg-gradient-to-br from-cyan-950 via-slate-900 to-indigo-950 p-6"><div className="flex items-center gap-2 text-cyan-300"><Users className="h-5 w-5" /><span className="text-xs font-bold uppercase tracking-[0.18em]">Community</span></div><h1 className="mt-3 text-2xl font-black text-white">Practise together.</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-slate-300">A calm space to share wins, ask language questions, and find encouragement from other English learners.</p></section>
    {isAuthenticated ? <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-4"><div className="flex items-center gap-2 text-sm font-bold text-white"><PenLine className="h-4 w-4 text-indigo-300" />Share a practice note</div><textarea value={draft} onChange={(event) => setDraft(event.target.value)} rows={3} placeholder="What did you practise today?" className="mt-3 w-full resize-none rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-indigo-400" /><button onClick={submitPost} disabled={!draft.trim()} className="mt-3 rounded-xl bg-indigo-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-40">Post to community</button></section> : <section className="flex items-center justify-between gap-4 rounded-2xl border border-indigo-500/20 bg-indigo-500/10 p-4"><div><p className="font-bold text-white">Join the conversation</p><p className="mt-1 text-xs text-slate-300">Sign in to share a post or reply. You can still read the community without an account.</p></div><button onClick={onSignIn} className="shrink-0 rounded-xl bg-white px-3 py-2 text-xs font-black text-slate-950">Sign in</button></section>}
    <section className="space-y-3">{posts.map((post) => { const isLiked = liked.includes(post.id); return <article key={post.id} className="rounded-2xl border border-slate-800 bg-slate-900/70 p-4"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 to-cyan-500 text-xs font-black text-white">{post.initials}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-sm font-bold text-white">{post.author}</p><span className="text-[11px] text-slate-500">{post.time}</span></div><h2 className="mt-3 font-bold text-white">{post.title}</h2><p className="mt-2 text-sm leading-relaxed text-slate-300">{post.body}</p><div className="mt-4 flex items-center gap-4 text-xs text-slate-500"><button onClick={() => toggleLike(post.id)} className={`flex items-center gap-1.5 ${isLiked ? "text-rose-300" : "hover:text-rose-300"}`}><Heart className={`h-4 w-4 ${isLiked ? "fill-current" : ""}`} />{post.likes + (isLiked ? 1 : 0)}</button><button className="flex items-center gap-1.5 hover:text-cyan-300"><MessageCircle className="h-4 w-4" />{post.replies} replies</button></div></div></div></article>; })}</section>
  </div>;
};
